# Source:
# - https://github.com/antfu/vscode-icons-carbon/blob/v0.2.4/.github/workflows/release.yml
# - https://github.com/actions/checkout#usage
# - https://github.com/pnpm/action-setup
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          registry-url: 'https://registry.npmjs.org/'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.25.1
          run_install: true
      - run: pnpm build
